name: Check style
on: push

jobs:
  check-style:
    name: Check style
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: "0"
            token: ${{ secrets.AUTH_TOKEN }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
            python-version: "3.10"
        
      - name: flake8
        run: |
            pip install flake8 

      - name: black
        run: |
             pip install black       

      - name: Check style
        run: ./py_files.sh

      - name: Commit changes
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
                author_name: PotencialGibsa
                author_email: shmygol.di@phsyetech.edu
                message: 'Improve with CICD'
                add: '.'